name: GitHub Actions Demo
run-name: Testing out GitHub Actions Event Trigger
'on':
  push: null
   branches:
    - main
    - releases/**
  pull_request: null
jobs:
  Basic-Workflow: null
  runs-on: ubuntu-latest
  steps:
    - run: echo " Job is executing as part of Basic workflow
